---
- name: test
  hosts: webservers
  gather_facts: false
  vars:
    ansible_ssh_user: user
  become: yes

  pre_tasks:
    - name: Validating the SSH port is open
      wait_for:
        host: "{{ (ansible_ssh_host | default(ansible_host)) | default(inventory_hostname) }}"
        port: 22
        delay: 5
        timeout: 300
        state: started
        search_regex: OpenSSH

  tasks:
    - name: Create test file
      copy:
        dest: /tmp/test
        content: "success"

    - name: Ensure Nginx is installed
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Gather service facts
      service_facts:

    - name: Check Nginx service status
      debug:
        msg: "Nginx is running: {{ ansible_facts.services['nginx.service'] is defined and ansible_facts.services['nginx.service'].state == 'running' }}"
